### ISSUE TITLE
Почему используется привязка guzzlehttp/guzzle к ~6.4.1?

### ISSUE THREAD

**Issue by gomzyakov** [avto-dev/cloud-payments-laravel#10]
Сейчас в `composer.json` есть довольно жесткое ограничение на версию Guzzle:

```json
"guzzlehttp/guzzle": "~6.4.1",
```

Если некий проект, в рамках которого уже используется Guzzle более свежей версии `6.5.5`. Возникает конфликт, *не критично*, но версию на проекте придётся понижать.

С чем связано использование именно `~6.4.1`, а не, допустим, `^6.4`? Какая-то специфика работы внутри пакета?

**Comment by jetexe** [comment]
Исправлено в новом релизе [v1.0.1](https://packagist.org/packages/avto-dev/cloud-payments-laravel)

Можете сделать:

```bash
$ composer update avto-dev/cloud-payments-laravel
```
