### ISSUE TITLE
Добавлен параметр Payer в метод для оплаты по криптограмме

### ISSUE THREAD

**Issue by gomzyakov** [avto-dev/cloud-payments-laravel#15]
18 января 2021 г. в API CloudPayments внесены обратно-совместимые [изменения](https://developers.cloudpayments.ru/#svodka-izmeneniy):

Параметр | Формат | Применение | Описание
-- | -- | -- | --
Payer | Object | Необязательный | Доп. поле, куда передается информация о плательщике. Используйте следующие параметры: `FirstName`, `LastName`, `MiddleName`, `Birth`, `Street`, `Address`, `City`, `Country`, `Phone`, `Postcode`

Для работы наших сервисов не критично, но, учитывая, что пакет `avto-dev/cloud-payments-laravel` открытый, кому-то может пригодиться.

**Comment by eldario** [comment]
Can u make a PR?

**Comment by gomzyakov** [comment]
@eldario Yes, I will do it during the day
